// source: src/CMSService.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.BlogPost', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.BlogPostComment', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.BlogPostComments', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.BlogPostRequest', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.BlogPosts', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.Empty', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement', null, global);
goog.exportSymbol('proto.com.trinad.cms.grpcserver.service.UserRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.BlogPostRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.BlogPostRequest.displayName = 'proto.com.trinad.cms.grpcserver.service.BlogPostRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.displayName = 'proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.displayName = 'proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.UserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.UserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.UserRequest.displayName = 'proto.com.trinad.cms.grpcserver.service.UserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.Empty.displayName = 'proto.com.trinad.cms.grpcserver.service.Empty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.BlogPost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.BlogPost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.BlogPost.displayName = 'proto.com.trinad.cms.grpcserver.service.BlogPost';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.trinad.cms.grpcserver.service.BlogPosts.repeatedFields_, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.BlogPosts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.BlogPosts.displayName = 'proto.com.trinad.cms.grpcserver.service.BlogPosts';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.displayName = 'proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.BlogPostComment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.BlogPostComment.displayName = 'proto.com.trinad.cms.grpcserver.service.BlogPostComment';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.trinad.cms.grpcserver.service.BlogPostComments.repeatedFields_, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.BlogPostComments, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.BlogPostComments.displayName = 'proto.com.trinad.cms.grpcserver.service.BlogPostComments';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.displayName = 'proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.BlogPostRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    bpId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pictureName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    picture: jspb.Message.getFieldWithDefault(msg, 5, ""),
    userIdentity: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.BlogPostRequest;
  return proto.com.trinad.cms.grpcserver.service.BlogPostRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBpId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPictureName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPicture(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserIdentity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.BlogPostRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBpId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPictureName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPicture();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUserIdentity();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional int64 bp_id = 1;
 * @return {number}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.getBpId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.setBpId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string picture_name = 4;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.getPictureName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.setPictureName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string picture = 5;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.getPicture = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.setPicture = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string user_identity = 6;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.getUserIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostRequest.prototype.setUserIdentity = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement}
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement;
  return proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement}
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement} returns this
 */
proto.com.trinad.cms.grpcserver.service.SuccessAcknowlegement.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    bpComId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    bpId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    comment: jspb.Message.getFieldWithDefault(msg, 3, ""),
    comParentId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    userIdentity: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest;
  return proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBpComId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBpId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setComParentId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserIdentity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBpComId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getBpId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getComment();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getComParentId();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getUserIdentity();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int64 bp_com_id = 1;
 * @return {number}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.getBpComId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.setBpComId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 bp_id = 2;
 * @return {number}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.getBpId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.setBpId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string comment = 3;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.setComment = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 com_parent_id = 4;
 * @return {number}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.getComParentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.setComParentId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string user_identity = 5;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.getUserIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.prototype.setUserIdentity = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.UserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.UserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    givenName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    familyName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    nickName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    email: jspb.Message.getFieldWithDefault(msg, 5, ""),
    picture: jspb.Message.getFieldWithDefault(msg, 6, ""),
    userIdentity: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.UserRequest;
  return proto.com.trinad.cms.grpcserver.service.UserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.UserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGivenName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFamilyName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNickName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPicture(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserIdentity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.UserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.UserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGivenName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFamilyName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNickName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPicture();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUserIdentity();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string given_name = 2;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.getGivenName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.setGivenName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string family_name = 3;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.getFamilyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.setFamilyName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string nick_name = 4;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.getNickName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.setNickName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string email = 5;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string picture = 6;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.getPicture = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.setPicture = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string user_identity = 7;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.getUserIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.UserRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.UserRequest.prototype.setUserIdentity = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.Empty}
 */
proto.com.trinad.cms.grpcserver.service.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.Empty;
  return proto.com.trinad.cms.grpcserver.service.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.Empty}
 */
proto.com.trinad.cms.grpcserver.service.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.BlogPost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.toObject = function(includeInstance, msg) {
  var f, obj = {
    bpr: (f = msg.getBpr()) && proto.com.trinad.cms.grpcserver.service.BlogPostRequest.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPost}
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.BlogPost;
  return proto.com.trinad.cms.grpcserver.service.BlogPost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPost}
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.trinad.cms.grpcserver.service.BlogPostRequest;
      reader.readMessage(value,proto.com.trinad.cms.grpcserver.service.BlogPostRequest.deserializeBinaryFromReader);
      msg.setBpr(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.BlogPost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBpr();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.trinad.cms.grpcserver.service.BlogPostRequest.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional BlogPostRequest bpr = 1;
 * @return {?proto.com.trinad.cms.grpcserver.service.BlogPostRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.getBpr = function() {
  return /** @type{?proto.com.trinad.cms.grpcserver.service.BlogPostRequest} */ (
    jspb.Message.getWrapperField(this, proto.com.trinad.cms.grpcserver.service.BlogPostRequest, 1));
};


/**
 * @param {?proto.com.trinad.cms.grpcserver.service.BlogPostRequest|undefined} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPost} returns this
*/
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.setBpr = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPost} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.clearBpr = function() {
  return this.setBpr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.hasBpr = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPost} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPost.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.BlogPosts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPosts} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.toObject = function(includeInstance, msg) {
  var f, obj = {
    bpList: jspb.Message.toObjectList(msg.getBpList(),
    proto.com.trinad.cms.grpcserver.service.BlogPost.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPosts}
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.BlogPosts;
  return proto.com.trinad.cms.grpcserver.service.BlogPosts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPosts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPosts}
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.trinad.cms.grpcserver.service.BlogPost;
      reader.readMessage(value,proto.com.trinad.cms.grpcserver.service.BlogPost.deserializeBinaryFromReader);
      msg.addBp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.BlogPosts.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPosts} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBpList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.trinad.cms.grpcserver.service.BlogPost.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BlogPost bp = 1;
 * @return {!Array<!proto.com.trinad.cms.grpcserver.service.BlogPost>}
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.prototype.getBpList = function() {
  return /** @type{!Array<!proto.com.trinad.cms.grpcserver.service.BlogPost>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.trinad.cms.grpcserver.service.BlogPost, 1));
};


/**
 * @param {!Array<!proto.com.trinad.cms.grpcserver.service.BlogPost>} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPosts} returns this
*/
proto.com.trinad.cms.grpcserver.service.BlogPosts.prototype.setBpList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPost=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPost}
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.prototype.addBp = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.trinad.cms.grpcserver.service.BlogPost, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPosts} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPosts.prototype.clearBpList = function() {
  return this.setBpList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    bpId: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest;
  return proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBpId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBpId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 bp_id = 1;
 * @return {number}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.prototype.getBpId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostCommentsRequest.prototype.setBpId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.BlogPostComment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostComment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.toObject = function(includeInstance, msg) {
  var f, obj = {
    bpcr: (f = msg.getBpcr()) && proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.toObject(includeInstance, f),
    createdTime: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComment}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.BlogPostComment;
  return proto.com.trinad.cms.grpcserver.service.BlogPostComment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostComment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComment}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest;
      reader.readMessage(value,proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.deserializeBinaryFromReader);
      msg.setBpcr(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedTime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.BlogPostComment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostComment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBpcr();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest.serializeBinaryToWriter
    );
  }
  f = message.getCreatedTime();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional BlogPostCommentRequest bpcr = 1;
 * @return {?proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.getBpcr = function() {
  return /** @type{?proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest} */ (
    jspb.Message.getWrapperField(this, proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest, 1));
};


/**
 * @param {?proto.com.trinad.cms.grpcserver.service.BlogPostCommentRequest|undefined} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComment} returns this
*/
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.setBpcr = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComment} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.clearBpcr = function() {
  return this.setBpcr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.hasBpcr = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string created_time = 2;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.getCreatedTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComment} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.setCreatedTime = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComment} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComment.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.BlogPostComments.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostComments} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.toObject = function(includeInstance, msg) {
  var f, obj = {
    bpcList: jspb.Message.toObjectList(msg.getBpcList(),
    proto.com.trinad.cms.grpcserver.service.BlogPostComment.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComments}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.BlogPostComments;
  return proto.com.trinad.cms.grpcserver.service.BlogPostComments.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostComments} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComments}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.trinad.cms.grpcserver.service.BlogPostComment;
      reader.readMessage(value,proto.com.trinad.cms.grpcserver.service.BlogPostComment.deserializeBinaryFromReader);
      msg.addBpc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.BlogPostComments.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostComments} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBpcList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.trinad.cms.grpcserver.service.BlogPostComment.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BlogPostComment bpc = 1;
 * @return {!Array<!proto.com.trinad.cms.grpcserver.service.BlogPostComment>}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.prototype.getBpcList = function() {
  return /** @type{!Array<!proto.com.trinad.cms.grpcserver.service.BlogPostComment>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.trinad.cms.grpcserver.service.BlogPostComment, 1));
};


/**
 * @param {!Array<!proto.com.trinad.cms.grpcserver.service.BlogPostComment>} value
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComments} returns this
*/
proto.com.trinad.cms.grpcserver.service.BlogPostComments.prototype.setBpcList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.trinad.cms.grpcserver.service.BlogPostComment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComment}
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.prototype.addBpc = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.trinad.cms.grpcserver.service.BlogPostComment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.trinad.cms.grpcserver.service.BlogPostComments} returns this
 */
proto.com.trinad.cms.grpcserver.service.BlogPostComments.prototype.clearBpcList = function() {
  return this.setBpcList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest}
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest;
  return proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest}
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest} returns this
 */
proto.com.trinad.cms.grpcserver.service.GetAllBlogPostsRequest.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.com.trinad.cms.grpcserver.service);
